name: Upload docker image

on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Versions
      uses: actions/github-script@v4
      id: set_version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          core.setOutput('no_v', no_v)
      
    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: ghcr.io/woodenmaiden/portfolio:${{ steps.set_version.outputs.no_v }},ghcr.io/woodenmaiden/portfolio:latest
